Music/urls.py
from django.urls import path
from . import views

app_name = 'music'


urlpatterns = [
    path('', views.index, name='index'),
    path('add_singer/', views.add_singer, name='add_singer'),
    path('add_album/', views.add_album, name='add_album'),
    path('add_song/', views.add_song, name='add_song'),
    path('album_list/<int:singer_id>/', views.album_list, name='album_list'),
    path('song_list/<int:album_id>/', views.song_list, name='song_list'),
    path('edit_singer/<int:singer_id>/', views.edit_singer, name='edit_singer'),
    path('edit_album/<int:album_id>/', views.edit_album, name='edit_album'),
    path('edit_song/<int:song_id>/', views.edit_song, name='edit_song'),
    path('delete_singer/<int:singer_id>/', views.delete_singer, name='delete_singer'),
    path('delete_album/<int:album_id>/', views.delete_album, name='delete_album'),
    path('delete_song/<int:song_id>/', views.delete_song, name='delete_song'),
]

Music_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Music.urls')),
]

Music/models.py
from django.db import models

# Create your models here.
class Singer(models.Model):
    name = models.CharField(max_length=50)
    instrument = models.CharField(max_length= 50)

    def __str__(self):
        return "{}".format(self.name)


class Album(models.Model):
    name = models.CharField(max_length=100)
    singer = models.ForeignKey(Singer, on_delete=models.CASCADE)
    release_date = models.DateField()
    num_star = ((1, 'Wrost'),(2,'Bad'),(3,'Not Bad'),(4,'Good'),(5,'Excellent!'))
    rating = models.IntegerField(choices=num_star)

    def __str__(self):
        return "{} by {}".format(self.name, self.singer)


class Song(models.Model):
    name = models.CharField(max_length=100)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    singer = models.ForeignKey(Singer, on_delete=models.CASCADE)
    other_singer = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return "{} form {} {}".format(self.name, self.album, self.other_singer)

Music/forms.py
from django import forms

from . import models



class SingerForm(forms.ModelForm):
    class Meta:
        model = models.Singer
        fields = "__all__"


class AbumForm(forms.ModelForm):
    release_date = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = models.Album
        fields = "__all__"


class SongForm(forms.ModelForm):
    class Meta:
        model = models.Song
        fields = "__all__"

Music/views.py
from django.shortcuts import render
from django.db.models import Avg

from . import models
from . import forms



# Create your views here.
def index(request):
    singer_list = models.Singer.objects.all()
    diction = {
        'title':'Home Page',
        'singer_list':singer_list,
    }
    return render(request, 'music/index.html', context=diction)


def album_list(request, singer_id):
    singer_info = models.Singer.objects.get(pk=singer_id)
    album_list = models.Album.objects.filter(singer=singer_info)
    singer_rating = models.Album.objects.filter(singer=singer_id).aggregate(Avg('rating'))
    diction = {
        'title':'Album List',
        'singer_info':singer_info,
        'album_list':album_list,
        'singer_rating':singer_rating,
    }
    return render(request, 'music/album_list.html', context=diction)


def song_list(request, album_id):
    album_info = models.Album.objects.get(pk=album_id)
    song_list = models.Song.objects.filter(album=album_id)
    diction = {
        'title':"Song List",
        'album_info':album_info,
        'song_list':song_list,
        'album_id':album_id,
    }
    return render(request, 'music/song_list.html', context=diction)


def add_singer(request):
    form = forms.SingerForm()
    if request.method == "POST":
        form = forms.SingerForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
    diction = {
        'title' :'Add Singer',
        'singer_form':form,
    }
    return render(request, 'music/singer_form.html', context=diction)


def add_album(request):
    form = forms.AbumForm()
    if request.method == "POST":
        form = forms.AbumForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
    diction = {
        'title': 'Add Album',
        'album_form' : form,
    }
    return render(request, 'music/album_form.html', context=diction)


def add_song(request):
    form = forms.SongForm()
    if request.method == "POST":
        form = forms.SongForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
    diction = {
        'title':'Add Song',
        'song_form':form,
    }
    return render(request, 'music/song_form.html', context=diction)


def edit_singer(request, singer_id):
    singer_info = models.Singer.objects.get(pk=singer_id)
    form = forms.SingerForm(instance=singer_info)
    diction = {}
    if request.method == "POST":
        form = forms.SingerForm(request.POST, instance=singer_info)
        if form.is_valid():
            form.save(commit=True)
            diction.update({'success_text':"Successfully Updated!"})
    diction.update({'title':"Edit Singer"})
    diction.update({'edit_singer':form})
    return render(request, 'music/edit_singer.html', context=diction)


def edit_album(request, album_id):
    album_info = models.Album.objects.get(pk=album_id)
    form = forms.AbumForm(instance=album_info)
    diction = {}
    if request.method == "POST":
        form = forms.AbumForm(request.POST, instance=album_info)
        if form.is_valid():
            form.save(commit=True)
            diction.update({'success_text':"Successfully Updated!"})
    diction.update({'title':"Edit Album"})
    diction.update({'edit_album': form})
    return render(request, 'music/edit_album.html', context=diction)


def edit_song(request, song_id):
    song_info = models.Song.objects.get(pk=song_id)
    form = forms.SongForm(instance=song_info)
    diction = {}
    if request.method == "POST":
        form = forms.SongForm(request.POST, instance=song_info)
        if form.is_valid():
            form.save(commit=True)
            diction.update({'success_text': "Successfully Updated!"})
    diction.update({'title':"Edit Song"})
    diction.update({'edit_song':form})
    diction.update({'song_id':song_id})
    return render(request, 'music/edit_song.html', context=diction)


def delete_singer(request, singer_id):
    singer = models.Singer.objects.get(pk=singer_id).delete()
    diction = {
        'title':"Delete",
        'delete_text': "Album Deleted Successfully!",
    }
    return render(request, 'music/delete.html', context=diction)


def delete_album(request, album_id):
    album = models.Album.objects.get(pk=album_id).delete()
    diction = {
        'title':"Delete",
        'delete_text':"Album Deleted Successfully!",
    }
    return render(request, 'music/delete.html', context=diction)


def delete_song(request, song_id):
    song = models.Song.objects.get(pk=song_id).delete()
    diction = {
        'title': "Delete",
        'delete_text': "Album Deleted Successfully!",
    }
    return render(request, 'music/delete.html', context=diction)

templates/music/album_form.html
{% extends 'music/base.html' %}
{% block body_block %}
    <h2>{{ title }}:</h2>
    <form action="" method="POST" style="padding-top: 25px;">
        {{ album_form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Add" name="subnit" class="btn btn-primary btn=md">
    </form>
{% endblock %}

templates/music/album_list.html
{% extends 'music/base.html' %}
{% block body_block %}
    <h3>Name: {{ singer_info.name }}</h3>
    <h3>Instrument: {{ singer_info.instrument }}</h3>
    <h3>Singer Rating: {{ singer_rating.rating__avg }}</h3>
    <br>
    <a href="{% url 'music:edit_singer' singer_id=singer_info.id %}" class="btn btn-info btn-md">Edit</a> <a href="{% url 'music:delete_singer' singer_id=singer_info.id %}"
        class="btn btn-danger btn-md" onclick="return confirm('Delete This Singer?')">Delete</a>
    <hr>
    <br>
    {% if album_list %}
        <h2>List of Album:</h2>
        <table class="table table-borderd" border="1">
            <tr>
                <th>Name</th>
                <th>Release Date</th>
                <th>Rating</th>
            </tr>
            {% for album in album_list %}
            <tr>
                <td><a href="{% url 'music:song_list' album_id=album.id %}">{{ album.name }}</a></td>
                <td>{{ album.release_date }}</td>
                <td>{{ album.rating }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>There is no Album.</h2>
    {% endif %}
{% endblock %}

templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <!-- jQuery Library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <title>{{ title }}</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark" style="padding-left: 10%;">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'music:index' %}">Home</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:add_singer' %}">Add Singer</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:add_album' %}">Add Album</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:add_song' %}">Add Song</a>
            </li>
        </ul>
    </nav>

    <div style="padding-left: 10%; padding-top: 2%;">
        {% block body_block %}

        {% endblock %}
    </div>
</body>
</html>

templates/music/delete.html
{% extends 'music/base.html' %}
{% block body_block %}
    <div class="alert alert-danger">
        {{ delete_text }}
    </div>
{% endblock %}

templates/music/edit_album.html
{% extends 'music/base.html' %}
{% block body_block %}
    <h2>{{ title }}:</h2>
    {% if success_text %}
        <div class="alert alert-success">
            {{ success_text }}
        </div>
    {% endif %}
    <form action="" method="POST">
        {{ edit_album.as_p }}
        {% csrf_token %}
        <input type="submit" value="Update" name="update" class="btn btn-success btn-md">
    </form>
{% endblock %}

templates/music/edit_singer.html
{% extends 'music/base.html' %}
{% block body_block %}
    <h2>{{ title }}:</h2>
    {% if success_text %}
    <div class="alert alert-success">
        {{ success_text }}
    </div>
    {% endif %}
    
    <form action="" method="POST">
        {{ edit_singer.as_p }}
        {% csrf_token %}
        <input type="submit" value="Update" name="update" class="btn btn-success btn-md">
    </form>
{% endblock %}

templates/music/edit_song.html
{% extends 'music/base.html' %}
{% block body_block %}
    <h2>{{ title }}:</h2>
    <form action="" method="POST">
        {{ edit_song.as_p }}
        {% csrf_token %}
        <input type="submit" value="Update" class="btn btn-success btn-md"> <a href="{% url 'music:delete_song' song_id=song_id %}"
            class="btn btn-danger btn-md" onclick="return confirm('Delete This Song?')">Delete</a>
    </form>
{% endblock %}

templates/music/index.html
{% extends 'music/base.html' %}
{% block body_block %}
        {% if singer_list %}
        <h2>List of Singer:</h2>
        <ol>
            {% for singer in singer_list %}
            <li>
                <h3><a href="{% url 'music:album_list' singer_id=singer.id %}">{{ singer.name }}</a></h3>
            </li>
            {% endfor %}
        </ol>
        {% else %}
        <h2>There is no Singer.</h2>
        {% endif %}
{% endblock %}

templates/music/singer_form.html
{% extends 'music/base.html' %}
{% block body_block %}
    <h2>{{ title }}:</h2>
    <form action="" method="POST" style="padding-top: 25px;">
        {{ singer_form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Add" name="subnit" class="btn btn-primary btn=md">
    </form>
{% endblock %}

templates/music/song_form.html
{% extends 'music/base.html' %}
{% block body_block %}
    <h2>{{ title }}:</h2>
    <form action="" method="POST" style="padding-top: 25px;">
        {{ song_form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Add" name="subnit" class="btn btn-primary btn=md">
    </form>
{% endblock %}

templates/music/song_list.html
{% extends 'music/base.html' %}
{% block body_block %}
    <h3>Album Name: {{ album_info.name }}</h3>
    <h3>Singer Name: {{ album_info.singer }}</h3>
    <h3>Release Date: {{ album_info.release_date }}</h3>
    <h3>Rating: {{ album_info.rating }}</h3>
    <br>
    <a href="{% url 'music:edit_album' album_id=album_info.id %}" class="btn btn-info btn-md">Edit</a> <a href="{% url 'music:delete_album' album_id=album_info.id %}"
        class="btn btn-danger btn-md" onclick="return confirm('Delete This Album?')">Delete</a>
    <hr>
    {% if song_list %}
        <h2>List of song:</h2>
        <ol>
            {% for song in song_list %}
            <li>
                <h3><a href="{% url 'music:edit_song' song_id=song.id %}">{{ song.name }}</a></h3>
            </li>
            {% endfor %}
        </ol>
    {% else %}
        <h2>There is no Song.</h2>
    {% endif %}
{% endblock %}